### ISSUE TITLE
Bug: Sinkronisasi OpenSID

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#100]
Ketika url yang dimasukan adalah url OpenSID API terdapat garis miring diakhir url maka  sinkronisasi akan gagal, sebaiknya dari sistem akan mendeteksi dan menghapus garis miring tersebut.

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/135
