### ISSUE TITLE
Tambah Tombol Ekspor dan Impor

### ISSUE THREAD

**Issue by kbrozi** [OpenSID/wiki-pbb#101]
Tambah Tombol Ekspor dan Impor
1. Subjek Pajak
2. Objek Pajak
mempermudah pengerjaan secara manual oleh operator dari luar sehingga hanya fokus pada operator Admin pada aplikasi saja

**Comment by mranca** [comment]
Sudah ada pak di bagian sppt

**Comment by scqolbu24** [comment]
issue ini kami tutup karena subjek dan objek pajak dapat di import melalui halaman SPPT, dapat diisi pada sheet yang sudah disediakan pada data contoh di halaman tersebut.
