### ISSUE TITLE
Nama Rayon hilang ketika import database versi 22.09.01

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#102]
Replikasi muncul error : 
Database masih menggunakan versi 22.09.01 di import ke database yang baru, kemudian setelah dicek nama rayon hilang pada menu sidebar.

![nama rayon hilang](https://user-images.githubusercontent.com/68048807/201778453-7fac46b0-ead6-4a0b-ae0f-3f00e42c5b05.JPG)

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/139
