### ISSUE TITLE
Data tidak terfilter saat di buka

### ISSUE THREAD

**Issue by mranca** [OpenSID/wiki-pbb#103]
Terjadi pada menu sppt, subjek pajak dan objek pajak

**Comment by scqolbu24** [comment]
Pak @mranca, Apakah yang dimaksud jika data terlalu banyak, data tersebut ditampilkan terlebih dahulu secara keseluruhan? yang pernah di ujicoba bareng?

**Comment by mranca** [comment]
Iya betul pak

**Comment by scqolbu24** [comment]
Perbaikan yang dilakukan:

- [x] Menampilkan Data Subjek Pajak
- [x] Menampilkan Data Objek Pajak
- [x] Menampilkan Data SPPT

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/148
