### ISSUE TITLE
tambahkan max length input luas objek pajak

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/wiki-pbb#105]
saat ini luas objek pajak terbatas sampai 9999 sedangkan ada kasus luas objek pajak lebih dari 9999

![image](https://user-images.githubusercontent.com/36557759/204243501-b3d2a5b6-936f-4d7f-87fe-c1cf1abf4368.png)

![image](https://user-images.githubusercontent.com/36557759/204243532-ccf0f2f3-8b71-456d-9700-6205e0f7ca30.png)

**Comment by scqolbu24** [comment]
issue ini sama dengan [issue #96 Maksimal karakter pada input luas](https://github.com/OpenSID/wiki-pbb/issues/96) dan sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/144
