### ISSUE TITLE
BUG: Sinkronisasi ke server OpenSID

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#106]
Ketika menggunakan https://api.berputar.opendesa.id/ berjalan **normal** dan dapat **sinkronsiasi**, namun terdapat laporan di grup Pelanggan Fitur OpenSID Premium yang mengalami **gagal sinkronisasi**, setelah dites bersama terdapat eror seperti berikut:

![desadruntenkulon1](https://user-images.githubusercontent.com/68048807/205416146-d0037fe1-3674-4713-a836-05658e1ba540.JPG)

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/150
