### ISSUE TITLE
terjadi bug pada latar login

### ISSUE THREAD

**Issue by mranca** [OpenSID/wiki-pbb#107]
latar login, Logo Aplikasi, Logo Surat dan favicon tidak bisa tampil meski sudah tersimpan

**Comment by scqolbu24** [comment]
Apakah sudah jalankan perintah php artisan storage:link ?
Ada di Panduan https://panduan.opendesa.id/id/pbb/instalasi#server-hosting poin 13

**Comment by mranca** [comment]
baik setelah saya jalankan php artisan storage:link dan sudah berhasil
