### ISSUE TITLE
Panduan 22.12.01 - 23.03.01

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-pbb#115]

**Comment by scqolbu24** [comment]
![dasbor5](https://user-images.githubusercontent.com/68048807/220935825-233c56ef-0c0c-4bec-8a8b-f0b7f45a25db.JPG)

![tampilkan-data-v22 12](https://user-images.githubusercontent.com/68048807/220880079-741af9cd-ff8f-4ddc-9546-95da21700ee8.jpg)

![tambah-data-v22 12](https://user-images.githubusercontent.com/68048807/220875203-7c4c1afd-96e7-4c82-9c59-8dec97173458.jpg)

![ubah datav22 12](https://user-images.githubusercontent.com/68048807/220876902-a74f9a49-dd01-4fa5-9f1a-a04d28441a6f.JPG)

![Gambar-1v22 12](https://user-images.githubusercontent.com/68048807/220932910-69c91083-cad0-48ca-878a-d45cc9e5b703.JPG)

![Subjek-Pajakv23 03](https://user-images.githubusercontent.com/68048807/220938503-1dfa5c86-f565-4b6e-9fec-145df0130d72.jpg)

![Tambah-datav22 12](https://user-images.githubusercontent.com/68048807/220942573-5040f335-dbb0-406a-9816-42f263689a39.JPG)

![Tambah-datav22 12-1](https://user-images.githubusercontent.com/68048807/221045486-8c721216-5cec-4972-9381-e9a4e2935362.JPG)

![Ubah Data-v22 12](https://user-images.githubusercontent.com/68048807/220942630-8e643428-cef5-4a71-a972-f19fc8df1459.JPG)

![Objek-Pajakv23 03 01](https://user-images.githubusercontent.com/68048807/220939198-92b80cc3-f5fc-4d78-86dd-20ad982a33fb.jpg)

**Comment by scqolbu24** [comment]
![Tampilkan-Datav23 03](https://user-images.githubusercontent.com/68048807/221058105-7dcd8db2-15e4-4dba-92a8-01e9b3c4bd79.jpg)

![Tambah-datav22 12](https://user-images.githubusercontent.com/68048807/221083821-5ba3a072-7758-4aa4-8e64-445c981aa4e7.jpg)

![Ubah-Datav22 12](https://user-images.githubusercontent.com/68048807/221085392-2594ec77-5b6d-428e-b6ce-a074a59cfddf.JPG)

![Salin-Data](https://user-images.githubusercontent.com/68048807/221091925-297042da-dcbb-420c-8e10-d7306f7d4ee3.jpg)

![Salin-Data1](https://user-images.githubusercontent.com/68048807/221111294-807c9138-ba2d-4c1f-a926-dbf0121a5a37.jpg)

![Salin-Data2](https://user-images.githubusercontent.com/68048807/221111310-0b4d6e7a-fe74-4a64-9caa-93d804a8bc31.jpg)

![Salin-Data3](https://user-images.githubusercontent.com/68048807/221113230-a6ec1792-adee-4127-9f72-70b17f26c826.jpg)

![Salin-Data4](https://user-images.githubusercontent.com/68048807/221113234-178ff71b-9610-45c0-a068-9c596d3f4472.jpg)

**Comment by scqolbu24** [comment]
![Pengaturan-6-v23 02](https://user-images.githubusercontent.com/68048807/221153171-a7c17dc2-b634-4184-bf2b-d51a4eae9e66.JPG)

![Pengaturanv23 02](https://user-images.githubusercontent.com/68048807/221153275-24e08af2-5aef-4c53-90ce-adf1233ceaca.JPG)

![Pengaturan-v23 02-1](https://user-images.githubusercontent.com/68048807/221154129-83d35586-7082-4b51-ba85-231379e2ae99.JPG)

**Comment by scqolbu24** [comment]
![database1](https://user-images.githubusercontent.com/68048807/221201908-94761d46-61c8-4acd-a725-451711e7fb8a.png)

![berhasil](https://user-images.githubusercontent.com/68048807/221203508-3be2cfea-3bba-45cc-af15-e7fb4fff87a2.JPG)

**Comment by FirlianiF** [comment]
https://panduan.opendesa.id/id/pbb/halaman-administrasi

**Comment by scqolbu24** [comment]
![Salin-data5](https://user-images.githubusercontent.com/68048807/221451204-df750fa5-5a4e-4e08-8fcc-d4c4888a5eb2.jpg)
![Salin-data6](https://user-images.githubusercontent.com/68048807/221451208-7fc5fcc6-7283-4cce-aa1c-670223164609.jpg)
![Salin-data7](https://user-images.githubusercontent.com/68048807/221451210-bd52db2b-cc25-4208-8ec6-a9ec358824d6.jpg)
![Salin-data8](https://user-images.githubusercontent.com/68048807/221451212-a327056f-15c3-42f8-b3b4-223c097eab00.jpg)
