### ISSUE TITLE
[BUG] Validasi pada Pengaturan Aplikasi

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#12]
Kode desa yang diinputkan memiliki panjang karakter 4 digit, namun ketika diinput maksimal 3 digit, apabila diubah dari phpmyadmin menjadi 4 digit muncul validasi "Kode Desa panjangnya tidak boleh melebihi 3 karakter." ketika diubah.

Cara replikasi :
1. Masuk Ke menu Pengaturan -> Aplikasi
2. Tambahkan Kode Desa karakter akan terbatasi 3 digit.

Harapannya:
validasi panjang karakter disesuaikan dengan Length/Values di database yaitu 5 digit sehingga ketika input data 4 digit dapat normal.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/pbb_desa/pull/66

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/70
