### ISSUE TITLE
Jumlah data tidak muncul pada halaman dashboard 

### ISSUE THREAD

**Issue by mranca** [OpenSID/wiki-pbb#120]
Data tidak muncul

**Comment by scqolbu24** [comment]
@mranca  data pada halaman dashboard hanya muncul di tahun yang berjalan, jadi pada halaman dashboar akan muncul setelah sudah ada data di tahun 2023

Solusiya dibuatkan pilihan periode yang akan ditampilkan pada dasbor.

**Comment by mranca** [comment]
@scqolbu24 apakah sudah release seperti itu di versi last update pbb ?

**Comment by scqolbu24** [comment]
@mranca versi terakhir belum seperti itu, issue ini kami targetkan di bulan ini dengan harapan rilis di versi 23.03.01.

**Comment by mranca** [comment]
@scqolbu24 terimakasih pak informasinya

**Comment by yogiperdana** [comment]
Sudah dikerjakan melalui https://github.com/OpenSID/pbb_desa/pull/163
