### ISSUE TITLE
Salin Data SPPT dari tahun sebelumnya atau berdasarkan pilihan tahun dengan disesuaikan pada tahun berjalan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#121]
Dibuatkan tombol untuk salin data tahun sebelumnya / memilih tahun tertentu kemudian di salin ke tahun berjalan. 

- [x] Salin per data sppt
- [x] Salin Berdasarkan Pilihan Tertentu
- [x] Salin Berdasarkan Tahun Tertentu

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/pbb_desa/pull/167
