### ISSUE TITLE
BUG: sinkronisasi alamat API menggunakan http

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#123]
ketika mencoba melakukan sinkroniasi dengan alamat API http data tidak muncul, sehingga sebaiknya dibuat default https
ketika input `htpp` / `https` / tanpa `http` dan `https` hasil akhirnya akan diperbaiki secara otomatis dengan default `https://`

**Comment by FirlianiF** [comment]
https://github.com/OpenSID/pbb_desa/pull/166
