### ISSUE TITLE
Tombol Batalkan pembayaran Hilang pada halaman SPPT jika status sudah lunas

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#125]
cek pada panduan https://panduan.opendesa.id/pbb/halaman-administrasi/sppt

Tombol batalkan pembayaran seharusnya ada jika status lunas.

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/165
