### ISSUE TITLE
backup file pengguna seperti folder desa

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/wiki-pbb#126]
belum tersedianya folder tersendiri untuk menyimpan file file yang di upload di pbb (foto pengguna dll) sehingga saat terjadi masalah pada server yang harus install ulang pengguna harus upload ulang

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/218
