### ISSUE TITLE
BUG: Icon tombol Salin SPPT menggunakan icon hapus dan warna menggunakan merah

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#129]
Icon tombol Salin SPPT seharusnya menggunakan icon salin serta warna seharusnya sesuai dengan warna pada kolom Aksi di tabel SPPT.
<img width="960" alt="2023-03-02_14h56_55" src="https://user-images.githubusercontent.com/68048807/222366624-9cb23ab5-c9f6-4b96-91a1-3f20e20e9bf3.png">

<img width="960" alt="2023-03-02_14h59_08" src="https://user-images.githubusercontent.com/68048807/222367033-c9d1f92c-0ead-45fd-90d6-7b10fd996f99.png">

<img width="960" alt="2023-03-02_15h00_42" src="https://user-images.githubusercontent.com/68048807/222367290-b0559075-d9af-460e-80db-8d85a804c048.png">

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/171
