### ISSUE TITLE
[BUG] Logo menutupi judul halaman dan menu dashboard

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#13]
Logo terlalu besar menutupi menutupi judul halaman dan menu dashboard.

<img width="80%" alt="logo" src="https://user-images.githubusercontent.com/68048807/162662720-313afb6e-21bc-44a6-a25e-6830ff7abc1b.PNG">

harapannya logo disesiakan dengan ukuran pada navbar.

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/pbb_desa/pull/67
