### ISSUE TITLE
Input Pagu Pajak Ketika Salin Data SPPT tahun sebelumnya

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#131]
Sudah tersedia salin data untuk tahun sebelumnya sangat membantu pengguna sehingga tidak perlu input lagi yang mungkin akan cukup lama, namun demikian akan lebih efisien jika pagu pajak dapat diubah ketika salin data tersebut.

<img width="960" alt="2023-03-02_15h06_14" src="https://user-images.githubusercontent.com/68048807/222368913-149df1f8-dfdb-4bce-bc1b-db975f68909c.png">

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/173
