### ISSUE TITLE
[BUG] Penamaan database pada konfigurasi .env

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#14]
Database default adalah pbb_opensid, 
apabila pada file .env nama databasenya selain default tersebut maka tidak berfungsi.
termasuk halaman-halaman yang lain pemanggilan database ke config->database pada default.

harapannya nama database sesuai dengan konfigurasi yang ada di .env dapat berfungsi

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/pbb_desa/pull/68
