### ISSUE TITLE
Logo pada halaman Login Erorr (tidak tampil)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#15]
Saat ini logo pada halaman login tidak dapat ditampilkan, seharusnya ada logo default opendesa.
kemudian apabila mau mengubah logo tersebut baru ke pengaturan -> aplikasi -> upload logo surat

<img width="100%" alt="login" src="https://user-images.githubusercontent.com/68048807/162692354-9526e5da-21d0-4d83-85f5-48b7a4c4e797.PNG">

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/69
