### ISSUE TITLE
BUG: pada halaman subjek pajak 

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#158]
![bug- subjek pajak](https://user-images.githubusercontent.com/68048807/229330585-e34a7f65-9cb6-48a9-b6f0-e21c7c490dd5.JPG)

**Comment by scqolbu24** [comment]
Penanganannya saat ini adalah:
A. Cara 1
1. Masuk ke menu aplikasi
2. isi opensid password
3. klik tombol simpan
4. klik tombol cek sinkronisasi opensid
5. buka kembali menu subjek pajak dan klik tombol tambah

B. cara 2
1. Masuk ke menu aplikasi
2. Hapus opensid url, opensid email, opensid password  
3. klik tombol simpan

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/178
