### ISSUE TITLE
Perbaiki Logo Navbar

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#16]
Logo navbar saat ini yang ditampilkan adalah logo opendesa, seharusnya dapat disesuaikan dengan logo desa masing-masing.

logo dapat disesuaikan seperti pada pengaturan -> aplikasi -> logo surat.

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/71
