### ISSUE TITLE
Install Baru tidak dapat jalankan migrate

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#162]
Terjadi di versi v2305.0.0

![Image](https://user-images.githubusercontent.com/68048807/236796057-5dd21077-6bdc-40f8-8a7c-10b370fbf94b.png)

testing Menggunakan localhost aman, testing menggunakan demopbb.opendesa.id aman, namun dicoba langsung diserver desa pelanggan terjadi eror

**Comment by scqolbu24** [comment]
Yang sudah dilakukan di localhost dan demopbb.opendesa.id berjalan lancar dan normal.

Yang sudah dilakukan pada server di desa yang mengalami eror:
1. Pengaturan Multi PHP yaitu OpenSID menggunakan 7.4 dan PBB 8.1
    Jalankan pada terminal php artisan migrate --seed terjadi eror
2. Pengaturan Multi PHP yaitu OpenSID menggunakan 7.4 dan PBB 8.0
    Jalankan pada terminal php artisan migrate --seed
3. Pengaturan Current PHP 8.1 
    Jalankan pada terminal php artisan migrate --seed terjadi eror

Pernah dilakukan di server lain terjadi ketika eror pada API
1. Pengaturan Multi PHP yaitu OpenSID menggunakan 7.4 dan PBB 8.1 terjadi eror
2. Pengaturan Multi PHP yaitu OpenSID menggunakan 7.4 dan PBB 8.0 normal

**Comment by FirlianiF** [comment]
https://panduan.opendesa.id/id/pbb/instalasi

**Comment by scqolbu24** [comment]
Sudah dibuatkan panduan https://panduan.opendesa.id/id/pbb/instalasi#error-saat-jalankan-perintah-migrasi
