### ISSUE TITLE
Data SPPT jika sudah terlalu banyak akan mengalami loading cukup lama

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#167]
Berdasarkan laporan dari `mr anca` di telegram bahwa akan terjadi pesan eror berikut jika data terlalu banyak sehingga akan loading terlalu lama.
![loading terlalu lama](https://github.com/OpenSID/wiki-pbb/assets/68048807/53ab10c4-a96e-4619-a1ac-28e91904fdca)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/183
