### ISSUE TITLE
Data Subjek Pajak jika sudah terlalu banyak akan mengalami loading cukup lama

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#168]
Berkaitan dengan issue https://github.com/OpenSID/wiki-pbb/issues/167
![loading terlalu lama1](https://github.com/OpenSID/wiki-pbb/assets/68048807/6e973c59-2bfa-432f-be5d-c4071bd79fd4)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/184
