### ISSUE TITLE
Setting Token (Sinkronisasi OpenSID)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#17]
Saat ini untuk memasukan token harus lewat database ubah dari phpmyadmin pada table tb_setting.
Seharusnya ada inputan untuk memasukan token pada Pengaturan -> Aplikasi.

**Comment by andifahruddinakas** [comment]
Coba cek alur kerjanya, token disimpan dari respon yg diterima dr api, sma seperti opensid->opendk.

Kalau tdk salqh ingat.

**Comment by scqolbu24** [comment]
Baik mas @andifahruddinakas, setelah dicek untuk input token melalui tombol "Test Sinkronisasi OpenSID".
issue ini dirubah dari fitur menjadi bug. dikarenakan tombol "Test Sinkronisasi OpenSID" belum berfungsi.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/72
