### ISSUE TITLE
Tampilkan pesan error dari server api ketika mengalami gagal sinkronisasi dengan OpenSID

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#171]
Ketika gagal sinkron pesan yang diberikan kurang spesifik, perlu ditambahkan pesan yang lebih memudahkan pengguna. Contoh kasus issue https://github.com/OpenSID/rilis-pbb/issues/4

Solusi :
Tampilkan juga pesan dari response api

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/187
