### ISSUE TITLE
Tidak dapat memperbarui token opensid

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#172]
Ketika token berhasil dibuat, maka tidak bisa melakukan update token kembali. Akan bermasalah jika token telah expired atau tidak valid di sisi opensid

case token invalid di opensid, edit value record dengan key opensid_token pada tabel pengaturan_aplikasi
Masuk ke menu pengaturan aplikasi, lakukan update token opensid. Jika token tidak kosong nilai token tidak bisa berubah

Yang diharapkan :
Pengguna bisa melakukan update token, barangkali token yang lama sudah tidak valid

**Comment by vickyrolanda** [comment]
mas @pandigresik silahkan baca komentar yang ada di issue ini ya mas https://github.com/OpenSID/wiki-pbb/issues/112 karena saling berkaitan.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/188
