### ISSUE TITLE
Bermasalah pada cetak rekap di aplikasi pbb desa Bangun kec Gunung Malela

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#173]
Terjadi error dengan code 500 berdasarkan informasi di trello https://trello.com/c/jHPYKm8c/30-desa-bangun-cetak-laporan-pbb

Replikasi : 
1. Masuk ke laporan - cetak rekap
2. Pilih tab Tanggal Bayar
3. Biarkan tanggalnya kosong
4. Klik sortir
5. Klik unduh
6. Terjadi error

Yang diharapkan :
Tidak terjadi error

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/wiki-pbb/assets/1853475/872a0a42-b8de-423a-8d23-83a38ad14570)

mode development

**Comment by vickyrolanda** [comment]
mas @pandigresik  issue ini butuh perbaikan jga , memang disable button itu bagian dari solusi tpi ketika menjalankan URL yang sy dapt dari inspect element tetap terjadi error seperti ini : 
![image](https://github.com/OpenSID/wiki-pbb/assets/59082428/6cba129a-6f96-4e82-8d9e-58bd2325008f)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/197
