### ISSUE TITLE
Terjadi error ketika buka menu rekap pembayaran - rekap waktu

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#174]
gunakan db pada https://trello.com/c/jHPYKm8c/30-desa-bangun-cetak-laporan-pbb
Replikasi :

1. Buka menu rekap pembayaran - rekap waktu
2. Terjadi error

![image](https://github.com/OpenSID/wiki-pbb/assets/1853475/48ab7f00-4a69-40d5-9e84-d58f65a39d4f)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/190
