### ISSUE TITLE
Error ketika buka menu rayon

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#175]
gunakan db pada https://trello.com/c/jHPYKm8c/30-desa-bangun-cetak-laporan-pbb
![image](https://github.com/OpenSID/wiki-pbb/assets/1853475/8a3dfe76-f359-48eb-9d22-1ddbb1d0d129)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/191
