### ISSUE TITLE
Pilihan tahun periode pada dashbord tidak menunjukkan tahun yang sesuai

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#176]
[Screencast from 02-08-23 14:40:19.webm](https://github.com/OpenSID/wiki-pbb/assets/1853475/4eb214a8-1182-47fd-a4be-83fc5acde196)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/192
