### ISSUE TITLE
Tombol hapus, batal bayar dan salin sppt tidak berfungsi

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#177]
Replikasi :
Masuk menu Transaksi - SPPT
Klik tombol selain edit pada salah satu SPPT
Tidak terjadi aksi apapun

[Screencast from 04-08-23 11:06:04.webm](https://github.com/OpenSID/wiki-pbb/assets/1853475/fe4d4e5e-0c32-4013-b2ae-8de4fe0a8eb0)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/196
