### ISSUE TITLE
Tambahkan validasi extension file pada upload foto modul pengaturan aplikasi

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#181]
Menu Pengaturan - Aplikasi

[Screencast from 11-08-23 13:55:10.webm](https://github.com/OpenSID/wiki-pbb/assets/1853475/362640dd-13a8-476a-b4b3-378026148c68)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/205
