### ISSUE TITLE
Tambahkan validasi extension file pada upload pengguna

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#182]
Menu Pengaturan - Pengguna

[Screencast from 11-08-23 14:01:58.webm](https://github.com/OpenSID/wiki-pbb/assets/1853475/568805fd-0353-4b39-991d-19859bbad5b8)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/207
