### ISSUE TITLE
Content Security Policy (CSP) Header Not Set

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#183]
Berdasarkan hasil uji otomatis owasp zap

Response : 
HTTP/1.1 404 Not Found
Host: 127.0.0.1:8000
Date: Thu, 10 Aug 2023 08:41:30 GMT
Connection: close
X-Powered-By: PHP/8.2.8
Cache-Control: no-cache, private
date: Thu, 10 Aug 2023 08:41:30 GMT
Content-Type: text/html; charset=UTF-8

Rekomendasi : 
Ensure that your web server, application server, load balancer, etc. is configured to set the Content-Security-Policy header.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/201
