### ISSUE TITLE
Cross-Domain JavaScript Source File Inclusion 

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#186]
Deskripsi : 
The page includes one or more script files from a third-party domain.

Contoh : 
<script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>

Rekomendasi: 
Ensure JavaScript source files are loaded from only trusted sources, and the sources can't be controlled by end users of the application.

Pastikan hanya mengambil code javascript hanya dari sumber yang terpercaya

**Comment by pandigresik** [comment]
Tidak ada PR khusus untuk issue ini
Secara otomatis terselesaikan dengan PR https://github.com/OpenSID/pbb_desa/pull/201

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/201
