### ISSUE TITLE
Informasi Server Leaks via "X-Powered-By" Header Respon HTTP Field 

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#187]
Deskripsi : 
Server web/aplikasi membocorkan informasi melalui satu atau lebih header respon HTTP "X-Powered-By". Akses terhadap informasi semacam itu dapat mempermudah penyerang untuk mengidentifikasi kerangka/komponen lain yang bergantung pada aplikasi web Anda dan kerentanan komponen semacam itu dapat dikenai.

Bukti : 
X-Powered-By: PHP/8.2.8 pada header

Rekomendasi : 
Pastikan server web, server aplikasi, penyeimbang beban, dan lain-lain dikonfigurasi untuk menekan header "X-Powered-By".

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/202
