### ISSUE TITLE
Ganti metode hapus file lama pada menu update foto aplikasi

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#190]
Menu :
Pengaturan - Aplikasi, ubah salah satu foto

Saat ini file yang dihapus berdasarkan request yang dikirim oleh form (field oldImage_), hal ini dapat dimanfaatkan oleh penyerang untuk menghapus file lain yang seharusnya tidak dihapus.

Solusi :
File yang dihapus bisa diambil dari database langsung, sehingga meminimalisir kesalahan

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/208
