### ISSUE TITLE
cek icon yang tidak tampil pada halaman admin

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-pbb#194]
1. halaman rekap lunas
![image](https://github.com/OpenSID/wiki-pbb/assets/59082428/061b620b-fabf-45a7-8fec-5886925212b2)

**Comment by pandigresik** [comment]
Memang iconnya seperti itu
https://datatables.net/extensions/searchpanes/examples/styling/bootstrap5.html

**Comment by vickyrolanda** [comment]
Issue ini sy hapus karena dugaan error ternyata sudah sesuai bukan terjadi error.
