### ISSUE TITLE
Bug: error ketika update versi 2309.0.0 di server siappakai

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#196]
Terjadi error setelah update ke versi 2309.0.0 pada server siappakai, namun hal ini tidak terjadi pada server demo pbb dengan alamat demopbb.opendesa.id dengan pesan error berikut ini :

![1693628297-206785-photo-6311996191923091473-y](https://github.com/OpenSID/wiki-pbb/assets/1853475/9460f47f-41f1-4ebc-852f-8e5a5b125cdb)

**Comment by yogiperdana** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/212
