### ISSUE TITLE
Bug: Tampilan catatan rilis tidak seperti versi 2308.0.0

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#197]
Tampilan catatan rilis kurang rapi , klik icon tanda tanya pojok kanan atas lalu cari bagian catatan rilis

![image](https://github.com/OpenSID/wiki-pbb/assets/1853475/797f0b6d-bcb7-4cc7-a6aa-3148fc39956b)

**Comment by yogiperdana** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/213
