### ISSUE TITLE
Tombol Sinkronisasi tidak dapat diklik dan beberapa tombol lain

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#198]
- [ ] Tombol sinkronisasi opensid tidak dapat diklik, replikasi 
Pilih menu pengaturan - Aplikasi
Klik tombol sinkronisai

![image](https://github.com/OpenSID/wiki-pbb/assets/1853475/e3749356-e5c2-42a7-9221-d793a6d3edc4)

- [ ] Tombol cetak pada rekap lunas ada pesan error
Pilih Laporan - rekap pembayaran - rekap lunas 
Klik tombol laporan rekap, pilih rayon dan RT akan timbul error di console

![image](https://github.com/OpenSID/wiki-pbb/assets/1853475/879fb239-c2bf-42d9-b62e-5e8ba251438f)

- [ ] Tombol detail objek pajak ( icon plus )
Pilih master data - objek pajak
Klik tombol tambah
Isi data, klik tombol tambah detail ( icon plus ) akan ada error di console

![image](https://github.com/OpenSID/wiki-pbb/assets/1853475/b3417585-5a8c-4203-a3d6-b88446e75ccb)

**Comment by yogiperdana** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/215
