### ISSUE TITLE
Tampilan dropdown select2 terlalu kecil pada halaman tambah subjek pajak

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-pbb#199]
![image](https://github.com/OpenSID/wiki-pbb/assets/1853475/598efba9-3929-4ade-9de4-48dcfa9c4ca6)

**Comment by yogiperdana** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/216
