### ISSUE TITLE
Sediakan arsip pbb setiap tahun

### ISSUE THREAD

**Issue by muhtar-coder** [OpenSID/wiki-pbb#2]
Saat ini data input PBB hanya untuk tahun berjalan,sedangkan pembayaran dan perubahan PBB ada setiap tahun.sehingga perlu di sediakan data arsip PBB setiap tahun atau data PBB tahun sebelumnya menjadi arsip desa sesuai pelaksanaan yang telah berjalan.

penambahan gambaran menu data PBB setiap tahun kurang lebih sebagai berikut :
![image](https://user-images.githubusercontent.com/55665526/161968700-47ff84b4-f305-46d1-b678-554e47384099.png)

**Comment by scqolbu24** [comment]
@muhtar-coder Nilai Total Pajak setiap tahunnya sama atau berbeda atau ada kemungkinan ada kenaikan?

**Comment by muhtar-coder** [comment]
Bisa berbeda tiap tahun

Pada tanggal Sen, 11 Apr 2022 11.19, sarwono ***@***.***>
menulis:

**Comment by scqolbu24** [comment]
Baik Pak, terimakasih

**Comment by muhtar-coder** [comment]
Info:
2 tahun terakhir,desa mendapatkan subsidi pbb. Misal dari 100 wajib pajak mendapat subsidi /gratis pajak sebanyak 70 wajib pajak.sehingga desa hanya wajib lunas senilai 30 wajib pajak.dari 100 wp tersebut.namun data rekap wajib yg di berikan dinas pajak tetap 100 wp.

**Comment by scqolbu24** [comment]
> Info: 2 tahun terakhir,desa mendapatkan subsidi pbb. Misal dari 100 wajib pajak mendapat subsidi /gratis pajak sebanyak 70 wajib pajak.sehingga desa hanya wajib lunas senilai 30 wajib pajak.dari 100 wp tersebut.namun data rekap wajib yg di berikan dinas pajak tetap 100 wp.

**Comment by scqolbu24** [comment]
> > Info: 2 tahun terakhir,desa mendapatkan subsidi pbb. Misal dari 100 wajib pajak mendapat subsidi /gratis pajak sebanyak 70 wajib pajak.sehingga desa hanya wajib lunas senilai 30 wajib pajak.dari 100 wp tersebut.namun data rekap wajib yg di berikan dinas pajak tetap 100 wp.

Dari subsidi tersebut, yang ditagihkan ke wp apakah dikurangi nilai subsidi ?

**Comment by FirlianiF** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/85
