### ISSUE TITLE
Sesuaikan readme dan lisensi untuk aplikasi PBB

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-pbb#206]
Readme pada https://github.com/OpenSID/rilis-pbb perlu diperjelas terkait mengapa adanya repo public. Sedangkan file lisensi mengatakan repo ini sumber terbuka. Padahal tidak, karena merupakan komponen yg dikhususkan bagi pelanggan Premium.

Sesuaikan readme memperjelas tujuan repo rilis.

Buat lisensi yg menjelaskan lisensi penggunaan PPB.

Naskah readme dan lisensi perlu disetujui oleh Direktur Pengembangan Aplikasi sebelum dirilis.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/229
