### ISSUE TITLE
Bug: Hasil Export SPPT tidak sesuai dengan isi data yang ada di database

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#207]
Pada saat export data SPPT hasil berbeda, di pelanggan muncul tahun 2023 padahal tidak ada data tahun 2023, kemudian untuk replikasi hasilnya 2022,
![pbb1](https://github.com/OpenSID/wiki-pbb/assets/68048807/ec17aaa8-fab0-4931-b0e7-891fef05541b)
![pbb2](https://github.com/OpenSID/wiki-pbb/assets/68048807/83f53317-94e8-4121-aa31-d50c3d9899fa)

Kemudian dari hasil export isis datanya berbeda misalkan Luas Objek Pajak Bumi, Luas Objek Pajak Bangunan, Klas Objek Bumi, Klas Objek Bangunan, NJOP Objek Pajak Bumi, NJOP Objek Pajak Bangunan, Total NJOP Objek Pajak Bumi, Total NJOP Objek Pajak Bangunan,

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/226
