### ISSUE TITLE
Bug: Tidak Dapat Input Angka 0 pada Blok di Objek Pajak

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#209]
Seharusnya bisa input angka 0 pada blok di Objek Pajak
![pbb4](https://github.com/OpenSID/wiki-pbb/assets/68048807/53ccf556-4929-4690-9036-4392a59300c1)

![pbb5](https://github.com/OpenSID/wiki-pbb/assets/68048807/5d85fc8e-0cf8-4ce9-a40e-e271251c1ee7)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/225
