### ISSUE TITLE
Bug/error:  Klik Cek Singkronisasi OpenSID tidak bisa singkronsinasi, data sudah sesuai panduan.

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/wiki-pbb#212]
Jelaskan error yg dialami :

Klik Cek Singkronisasi OpenSID tidak bisa singkronsinasi, data sudah sesuai panduan.

Cara untuk mereplikasi errornya :
1. https://demopbb.opendesa.id
2. Menu Aplikasi
3. Klik Cek Singkronisasi OpenSID

Tangkapan layar dan log error

![image](https://github.com/OpenSID/wiki-pbb/assets/55429781/386b3bbb-05db-4697-a425-cd31cf710da1)

Versi PBB
Aplikasi PBB v2312.0.0

**Comment by pandigresik** [comment]
Kami coba aman saja, kalau dari pesan error kemungkinan memang salah set pengaturan aplikasi saja. Pada video alamat saya ubah menjadi http bukan https karena di local saya tidak support https

[Screencast from 17-08-24 10:47:53.webm](https://github.com/user-attachments/assets/d0426241-a153-4bfe-a8ca-93b42d48d280)

**Comment by vickyrolanda** [comment]
Sudah direplikasi oleh mas afandi & mas ridho bahwa issue diatas sudah teratasin

**Comment by rgrahardi** [comment]
sudah saya update di panduan cek singkronisasi pbb dan opensid mas

https://panduan.opendesa.id/pbb/halaman-administrasi/aplikasi#sinkronisasi-opensid
