### ISSUE TITLE
Rekap Pembayaran berdasarkan Rekap Waktu (konversi ke laravel)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#33]
Tahapan issue [#9 Bertahap konversi ke laravel untuk rilis 22.06](https://github.com/OpenSID/wiki-pbb/issues/9)

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui pr https://github.com/OpenSID/pbb_desa/pull/94
