### ISSUE TITLE
Cetak Rekap (konversi ke laravel)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#34]
Tahapan issue [#9 Bertahap konversi ke laravel untuk rilis 22.06](https://github.com/OpenSID/wiki-pbb/issues/9)

Daftar Ceklist :
- [x] Sortir Penerimaan Rayon
- [x] Sortir Bulan Rayon
- [x] Sortir Tanggal Rayon
- [x] Sortir Tanggal Bayar
- [x] Sortir Penyetoran Bank
- [x] Unduh Penerimaan Rayon
- [x] Unduh Bulan Rayon
- [x] Unduh Tanggal Rayon
- [x] Unduh Tanggal Bayar
- [x] Unduh Penyetoran Bank

**Comment by vickyrolanda** [comment]
Hasil Review : 
Daftar Ceklist :
- [x] Sortir Penerimaan Rayon
- [x] Sortir Bulan Rayon
       - laporan bulan rayon data tidak berubah sesuai filter dan export excel tidak ada data.
<img width="869" alt="image" src="https://user-images.githubusercontent.com/59082428/186134152-c0b7121d-9b29-4ef7-b5d5-7b69bd2d20ce.png">

- [x] Sortir Tanggal Rayon
- [x] Sortir Tanggal Bayar
- [x] Sortir Penyetoran Bank
- [x] Unduh Penerimaan Rayon
- [x] Unduh Bulan Rayon
- [x] Unduh Tanggal Rayon
- [x] Unduh Tanggal Bayar
- [x] Unduh Penyetoran Bank

- [x] Check Reset Data tabel karena ketika tidak di refresh maka data dari tab sebelumnya ikut muncul.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/115
