### ISSUE TITLE
Gambar Panduan 22.07.01 sampai 22.11.01

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#35]
- [x] Halaman Dasbor
- [x] Halaman Login
- [x] Halaman Setel Ulang Kata Sandi
- [x] Halaman Rayon
- [x] Halaman RT
- [x] Halaman Periode
- [x] Halaman Subjek Pajak
- [x] Halaman Objek Pajak
- [x] Halaman SPPT
- [x] Halaman Pembayaran
- [x] Halaman Rekap Pembayaran
- [x] Cetak Rekap
- [x] Pengaturan Aplikasi
- [x] Pengaturan Pengguna
- [x] Sinkronisasi OpenSID

**Comment by scqolbu24** [comment]
![download source code](https://user-images.githubusercontent.com/68048807/176839094-871f0f8e-994c-486d-8c12-f6980e1f9b6d.JPG)

**Comment by scqolbu24** [comment]
![terminal cpanel](https://user-images.githubusercontent.com/68048807/176850202-785ae85c-36aa-4401-ba6a-ebe8a813bfac.JPG)

**Comment by scqolbu24** [comment]
![login](https://user-images.githubusercontent.com/68048807/192729722-bef1d427-7ca4-4cff-ac4a-0eac5a8a7032.JPG)

![dasbor-fix](https://user-images.githubusercontent.com/68048807/192757364-64b5575d-a1bb-4c5d-bb2e-84b658f23cb0.JPG)

**Comment by scqolbu24** [comment]
Halaman Rayon
![Gambar-1](https://user-images.githubusercontent.com/68048807/192920747-4f36f3ae-0454-43fa-b34c-4814b68e8906.JPG)
![Gambar-2](https://user-images.githubusercontent.com/68048807/192920350-05bd2a5e-b5ac-4770-adf2-5d9e331a7c47.JPG)
![Gambar-3](https://user-images.githubusercontent.com/68048807/192920353-ee5acd5c-1933-4331-a9a6-0a4b112a47cb.JPG)
![Gambar-4](https://user-images.githubusercontent.com/68048807/192920356-2e6b24f7-765e-4340-a86b-2801c26b5151.JPG)
![Gambar-5](https://user-images.githubusercontent.com/68048807/192920359-4c95feeb-3025-44e2-8ffd-00d6f422c7c3.JPG)

**Comment by scqolbu24** [comment]
Halaman RT
![Gambar-1](https://user-images.githubusercontent.com/68048807/193074447-106efd7c-e43d-4441-aae5-3a08b16fd0ea.JPG)
![Gambar-2](https://user-images.githubusercontent.com/68048807/193073709-29de331e-2863-49f2-936c-5845ba1e4670.JPG)
![Gambar-3](https://user-images.githubusercontent.com/68048807/193073710-d8ea8f0c-1831-447f-810c-df425a0461b1.JPG)
![Gambar-4](https://user-images.githubusercontent.com/68048807/193073713-13442572-27cf-4755-8037-3b149a4a3cf8.JPG)
![Gambar-5](https://user-images.githubusercontent.com/68048807/193073719-7e6c8788-7dba-4086-a5ac-e591a9990a36.JPG)

**Comment by scqolbu24** [comment]
Halaman Periode
![Gambar1](https://user-images.githubusercontent.com/68048807/193152933-c3a9b067-1f98-4602-a261-94e52d86fadb.jpg)
![Gambar2](https://user-images.githubusercontent.com/68048807/193152944-a9fc732c-a506-47a5-aed7-8fe5f67dfa33.jpg)
![Gambar3](https://user-images.githubusercontent.com/68048807/193152947-7fc07449-3f08-4b6a-9ea0-94ef81435b05.jpg)
![Gambar4](https://user-images.githubusercontent.com/68048807/193152951-5cc9a5f1-6d01-4463-ad72-ca9c0d398ba4.JPG)

**Comment by scqolbu24** [comment]
Halaman setel ulang kata sandi
![setel ulang](https://user-images.githubusercontent.com/68048807/193189850-47ca89a1-7ada-4e9f-ba4e-e325789e4e07.JPG)
![setel ulang-1](https://user-images.githubusercontent.com/68048807/193189854-9f10bf9e-f993-4607-ba65-6d0317502d74.JPG)
![setel ulang-2](https://user-images.githubusercontent.com/68048807/193189860-c7b34be1-4808-4304-9628-f72bf7c2c8e8.JPG)
![setel ulang-3](https://user-images.githubusercontent.com/68048807/193189861-d76f1201-6a44-4a86-94d8-e405439aaf33.JPG)

**Comment by scqolbu24** [comment]
Halaman Subjek Pajak
![Gambar1](https://user-images.githubusercontent.com/68048807/193247794-ca3d8f78-f51f-458c-a871-fbca7d60a55a.jpg)
![Gambar2-1](https://user-images.githubusercontent.com/68048807/199138633-49e691bf-95b2-4765-96a9-0d7a83e5eec7.jpg)
![Gambar2-2](https://user-images.githubusercontent.com/68048807/199138643-dd1ef761-ff1b-4c9d-b359-7a2c3150eaf8.jpg)
![Gambar3-1](https://user-images.githubusercontent.com/68048807/199138644-2ef63f87-183f-4ab9-b5f9-5f79ee525548.jpg)
![Gambar4](https://user-images.githubusercontent.com/68048807/193245558-1c8cb131-1f08-40f8-8649-30509c80cd16.JPG)

**Comment by scqolbu24** [comment]
Halaman Objek Pajak
![Gambar1](https://user-images.githubusercontent.com/68048807/193253859-502b7bdd-f4f2-4677-895f-214c9e5ed6a5.jpg)
![Gambar2](https://user-images.githubusercontent.com/68048807/193253868-a1a4b928-3883-4325-b2a0-f483598e4372.jpg)
![Gambar3](https://user-images.githubusercontent.com/68048807/193253873-c8c33c46-841a-49b2-a0d6-868309dc6784.jpg)
![Gambar4](https://user-images.githubusercontent.com/68048807/193253878-e77f39bd-9b08-4f5f-9973-725172fee636.jpg)
![Gambar5](https://user-images.githubusercontent.com/68048807/193253882-b0045f4a-c663-48bc-9341-cf0022e5c349.JPG)
![Gambar6](https://user-images.githubusercontent.com/68048807/193253883-7d82aa49-2e3b-49d7-bca1-22a98b003a42.JPG)
![Gambar7](https://user-images.githubusercontent.com/68048807/193253888-1f0ba403-080f-48ed-a0ca-d352720c2d8a.JPG)
![Gambar8](https://user-images.githubusercontent.com/68048807/193253889-f14f91c5-510e-4a16-bb22-390d40200c34.JPG)

**Comment by scqolbu24** [comment]
Halaman Pengaturan Aplikasi
![Pengaturan](https://user-images.githubusercontent.com/68048807/199128463-f8ada085-4ccf-4361-b390-22f0354e02e7.png)

![Pengaturan-5](https://user-images.githubusercontent.com/68048807/199131286-0fa361f9-5666-4982-88c9-f8c353f855e3.JPG)
![Pengaturan-6](https://user-images.githubusercontent.com/68048807/199131288-1718708d-d8cd-4e03-9e08-2aed04c445c4.JPG)

**Comment by scqolbu24** [comment]
Halaman Pembayaran
![Gambar1](https://user-images.githubusercontent.com/68048807/199209932-eb1a58b6-fa03-4aae-b253-b40008c0cc90.jpg)

**Comment by scqolbu24** [comment]
Pengaturan Pengguna
![Gambar1](https://user-images.githubusercontent.com/68048807/199351767-b1ac591f-debe-47f5-a81d-763bda2ba675.jpg)
![Gambar2](https://user-images.githubusercontent.com/68048807/199351771-4517922b-05ff-4e11-99bb-1fa349b04d1d.jpg)
![Gambar3](https://user-images.githubusercontent.com/68048807/199351773-70f1e698-0bff-4478-8efd-88e9258dfab1.jpg)
![Hapus Data](https://user-images.githubusercontent.com/68048807/199351064-e253e235-b69d-4773-9dc2-10821d3576f1.JPG)

**Comment by scqolbu24** [comment]
Halaman SPPT:
![Gambar1](https://user-images.githubusercontent.com/68048807/199356936-0fc55979-293d-4e3d-ba07-b9b3fe12dc01.jpg)
![Gambar2](https://user-images.githubusercontent.com/68048807/199356941-29be66ce-69cb-4079-8a9d-5af7d4e569ef.jpg)
![Gambar3](https://user-images.githubusercontent.com/68048807/199356942-1b589d9f-e8d3-4972-a83e-2683e37882fe.jpg)
![Gambar4](https://user-images.githubusercontent.com/68048807/199356944-1fa06876-e13a-4b85-8daa-2d0deb540156.JPG)
![Gambar5](https://user-images.githubusercontent.com/68048807/199360631-465f424e-2e32-4b56-803e-93eebdfb316f.jpg)
![Gambar6](https://user-images.githubusercontent.com/68048807/199356950-8d9114dc-615f-4fbc-8e4a-2704db205473.JPG)
![Gambar7](https://user-images.githubusercontent.com/68048807/199356953-9a5625c6-d6fe-4976-bc74-278a13f107d8.JPG)
![Gambar8](https://user-images.githubusercontent.com/68048807/199356958-34fbc242-7ddd-447b-b19f-49c204efabeb.jpg)

**Comment by scqolbu24** [comment]
Rekap Belum Bayar:
![Gambar1](https://user-images.githubusercontent.com/68048807/199514255-41ae1367-c14a-4516-98c5-096ac7c192f5.jpg)
![Gambar2-1](https://user-images.githubusercontent.com/68048807/199522347-3dfbb2d1-f643-49b3-85a3-16abcf536ada.jpg)
![Gambar3](https://user-images.githubusercontent.com/68048807/199446864-b808f8d7-4b1e-4411-91f1-9ceb678d72eb.jpg)

**Comment by scqolbu24** [comment]
Rekap Lunas:
![Gambar1](https://user-images.githubusercontent.com/68048807/199449510-63d5391d-f81b-4373-8b19-c8aa9bd8339e.jpg)
![Gambar2-1](https://user-images.githubusercontent.com/68048807/199522440-93cf155c-83d1-4893-b54f-48601d581e24.jpg)
![Gambar3](https://user-images.githubusercontent.com/68048807/199449522-5255b5d2-00f3-4d2b-8f47-4b167a87bf66.jpg)

**Comment by scqolbu24** [comment]
Rekap Waktu:
![Gambar1](https://user-images.githubusercontent.com/68048807/199506433-ac11b400-6bdf-4725-8880-613b1dcbebd9.jpg)
![Gambar2](https://user-images.githubusercontent.com/68048807/199456984-ed2019d2-cea1-40d4-be82-e024442cd198.jpg)
![Gambar3](https://user-images.githubusercontent.com/68048807/199456991-c740a6ad-0a18-4e33-9a73-5d099b45d97c.jpg)

**Comment by scqolbu24** [comment]
Cetak Rekap:

![Menampilkan-Cetak-Rekap](https://user-images.githubusercontent.com/68048807/199459866-b27afb6a-d5cd-4461-bf85-b5a4b04e26b1.jpg)

1. Penerimaan Rayon
![Sortir1](https://user-images.githubusercontent.com/68048807/199494722-095c647f-f34f-4ebd-9b7e-73d7fb984f3b.jpg)
![unduh1](https://user-images.githubusercontent.com/68048807/199494729-7fbb18cb-1550-4fef-b679-244def7dff8d.JPG)

2. Bulan Rayon
![sortir2](https://user-images.githubusercontent.com/68048807/199494766-2efd25b6-0f76-4ba9-b082-38241634c8ef.JPG)
![unduh2](https://user-images.githubusercontent.com/68048807/199494772-18dd3a4a-aaf9-47db-b803-70344280bca1.JPG)

3. Tanggal Rayon
![sortir-tanggal-rayon1](https://user-images.githubusercontent.com/68048807/199494815-86dbbd06-8a32-4778-b56e-74f5768be9e0.jpg)
![sortir-tanggal-rayon2](https://user-images.githubusercontent.com/68048807/199494823-462cf1ed-62e1-4c05-aedb-6fe0351d6fda.jpg)
![unduh3](https://user-images.githubusercontent.com/68048807/199494827-372e8236-2d05-4c29-a799-d87435e0ef24.JPG)

4. Tanggal Bayar
![tanggal-bayar1](https://user-images.githubusercontent.com/68048807/199494887-5fd0cc37-b60b-4f1d-9700-1842e09e8879.jpg)
![tanggal-bayar2](https://user-images.githubusercontent.com/68048807/199494894-7d42e5b7-7cb2-4022-b99f-613586c63d57.jpg)
![unduh4](https://user-images.githubusercontent.com/68048807/199494896-42b6b257-a1d5-4fb3-840d-a9c46e96d8f2.JPG)

5. Penyetoran
![penyetoran1](https://user-images.githubusercontent.com/68048807/199494980-e6009930-c3c1-485a-8f72-788ec648b293.jpg)
![penyetoran2](https://user-images.githubusercontent.com/68048807/199494984-6522828b-c47c-410d-8d99-00fd305af67e.jpg)
![unduh5](https://user-images.githubusercontent.com/68048807/199494989-87cca0c6-a662-4d5f-800e-1f0efbb8e118.JPG)

**Comment by scqolbu24** [comment]
Ceklist Panduan yang sudah dibuat
- [x] Halaman Dasbor https://panduan.opendesa.id/id/pbb/halaman-administrasi
- [x] Halaman Login https://panduan.opendesa.id/id/pbb/halaman-administrasi/login
- [x] Halaman Setel Ulang Kata Sandi https://panduan.opendesa.id/id/pbb/halaman-administrasi/setel-ulang-kata-sandi
- [x] Halaman Rayon https://panduan.opendesa.id/pbb/halaman-administrasi/rayon
- [x] Halaman RT https://panduan.opendesa.id/pbb/halaman-administrasi/rt
- [x] Halaman Periode https://panduan.opendesa.id/pbb/halaman-administrasi/periode
- [x] Halaman Subjek Pajak https://panduan.opendesa.id/pbb/halaman-administrasi/subjek-pajak
- [x] Halaman Objek Pajak https://panduan.opendesa.id/pbb/halaman-administrasi/objek-pajak
- [x] Halaman SPPT https://panduan.opendesa.id/pbb/halaman-administrasi/sppt
- [ ] Halaman Pembayaran https://panduan.opendesa.id/pbb/halaman-administrasi/pembayaran
- [x] Halaman Rekap Pembayaran 
       https://panduan.opendesa.id/pbb/halaman-administrasi/rekap-waktu
       https://panduan.opendesa.id/pbb/halaman-administrasi/rekap-belum-bayar
       https://panduan.opendesa.id/pbb/halaman-administrasi/rekap-lunas
- [x] Cetak Rekap https://panduan.opendesa.id/pbb/halaman-administrasi/cetak-rekap
- [x] Pengaturan Aplikasi https://panduan.opendesa.id/pbb/halaman-administrasi/aplikasi
- [x] Pengaturan Pengguna https://panduan.opendesa.id/pbb/halaman-administrasi/pengguna
- [x] Sinkronisasi OpenSID https://panduan.opendesa.id/pbb/halaman-administrasi/aplikasi#sinkronisasi-opensid

**Comment by devrakapriyo** [comment]
> Ceklist Panduan yang sudah dibuat
> 
> * [x]  Halaman Dasbor https://panduan.opendesa.id/id/pbb/halaman-administrasi
> * [x]  Halaman Login https://panduan.opendesa.id/id/pbb/halaman-administrasi/login
> * [x]  Halaman Setel Ulang Kata Sandi https://panduan.opendesa.id/id/pbb/halaman-administrasi/setel-ulang-kata-sandi
> * [x]  Halaman Rayon https://panduan.opendesa.id/pbb/halaman-administrasi/rayon
> * [x]  Halaman RT https://panduan.opendesa.id/pbb/halaman-administrasi/rt
> * [x]  Halaman Periode https://panduan.opendesa.id/pbb/halaman-administrasi/periode
> * [x]  Halaman Subjek Pajak https://panduan.opendesa.id/pbb/halaman-administrasi/subjek-pajak
> * [x]  Halaman Objek Pajak https://panduan.opendesa.id/pbb/halaman-administrasi/objek-pajak
> * [x]  Halaman SPPT https://panduan.opendesa.id/pbb/halaman-administrasi/sppt
> * [x]  Halaman Pembayaran https://panduan.opendesa.id/pbb/halaman-administrasi/pembayaran
> * [x]  Halaman Rekap Pembayaran
>   https://panduan.opendesa.id/pbb/halaman-administrasi/rekap-waktu
>   https://panduan.opendesa.id/pbb/halaman-administrasi/rekap-belum-bayar
>   https://panduan.opendesa.id/pbb/halaman-administrasi/rekap-lunas
> * [x]  Cetak Rekap https://panduan.opendesa.id/pbb/halaman-administrasi/cetak-rekap
> * [x]  Pengaturan Aplikasi https://panduan.opendesa.id/pbb/halaman-administrasi/aplikasi
> * [x]  Pengaturan Pengguna https://panduan.opendesa.id/pbb/halaman-administrasi/pengguna
> * [x]  Sinkronisasi OpenSID https://panduan.opendesa.id/pbb/halaman-administrasi/aplikasi#sinkronisasi-opensid

mas @scqolbu24 setelah saya review, untuk panduan Halaman Pembayaran harap lebih di detailkan, karena panduan ini tidak menjelaskan cara mengisi form pembayaran

**Comment by scqolbu24** [comment]
@devrakapriyo sudah diperbarui, silakan bisa dicek kembali

**Comment by devrakapriyo** [comment]
ok mas @scqolbu24 sudah sesuai
