### ISSUE TITLE
Pengaturan Bahasa

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#38]

**Comment by scqolbu24** [comment]
https://www.youtube.com/watch?v=ukyrS43kbSc
https://stackoverflow.com/questions/48535932/datatables-warning-table-id-example-cannot-reinitialise-datatable-for-more-i

**Comment by FirlianiF** [comment]
PR https://github.com/OpenSID/pbb_desa/pull/145
