### ISSUE TITLE
Atribute Validation

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#39]

**Comment by scqolbu24** [comment]
https://kursuswebprogramming.com/membuat-error-validasi-di-laravel-menjadi-bahasa-indonesia/

**Comment by scqolbu24** [comment]
https://stackoverflow.com/questions/48535932/datatables-warning-table-id-example-cannot-reinitialise-datatable-for-more-i

**Comment by FirlianiF** [comment]
PR https://github.com/OpenSID/pbb_desa/pull/145
