### ISSUE TITLE
Akun Pengguna untuk Demo

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#41]
**Apa kekurangan yg ingin diatasi?**
Saat ini akun admin pada web demo pbb https://demopbb.opendesa.id/ dapat ditambahkan, diubah, maupun dihapus oleh pengguna yang melakukan uji coba.

**Jelaskan solusi yg diinginkan**
Harapan dari fitur ini adalah ada satu akun yang secara default tidak dapat dirubah seperti halnya akun pengguna admin pada OpenSID dengan password sid304.

Tujuannya adalah:

Sebagai akun demo di https://demopbb.opendesa.id/.

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/97
