### ISSUE TITLE
Objek Pajak

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#43]
Sebelum mengerjakan issue https://github.com/OpenSID/wiki-pbb/issues/7, maka perlu adanya form objek pajak terlebih dahulu dan sesuai dengan tahapan konversi ke laravel https://github.com/OpenSID/wiki-pbb/issues/9 pada struktur database memerlukan table objek pajak.

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/82
