### ISSUE TITLE
Kumpulan Hasil Testing Aplikasi PBB

### ISSUE THREAD

**Issue by jonitrisulasmono** [OpenSID/wiki-pbb#45]
1. Link tidak Valid/tidak tersedia, tidak bisa download : https://github.com/OpenSID/pbb_desa,

2. Menu **Objek Pajak** ERROR  : 
ErrorException
Trying to get property 'nama_rt' of non-object (View: /home/demopbb.opendesa.id/pbb_desa/resources/views/pages/master-data/objek-pajak/index.blade.php)
https://demopbb.opendesa.id/objek-pajak

3. **Laporan Pembayaran** masih Not Found Semua..

**Comment by scqolbu24** [comment]
Terimakasih telah melakukan testing hal ini akan membantu pengembangan aplikasi pbb. Jawaban untuk Poin-poin diatas:
1. Link https://github.com/OpenSID/pbb_desa merupakan private, hanya yang memiliki akses dapat membuka link tersebut. untuk link yang dapat diakses untuk umum adalah https://github.com/OpenSID/rilis-pbb yang nantinya berisi rilis, namun saat ini masih kosong, jika sudah ada akan diinformasikan.
2. Menu Objek Pajak ERROR : Termasuk BUG akan segera diperbaiki.
3. Untuk Pembayaran masih proses konversi dapat dilihat pada issue https://github.com/OpenSID/wiki-pbb/issues/9, nomor 12 dan 13.

**Comment by jonitrisulasmono** [comment]
Terima kasih atas tanggapan.
Responsif banget Pengurusnya, makin semangat mencari bug.

**Comment by FirlianiF** [comment]
No. 2 sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/90
