### ISSUE TITLE
Buat Tombol Batalkan pembayaran (konversi ke laravel).

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#49]
Tahapan issue [#9 Bertahap konversi ke laravel untuk rilis 22.06](https://github.com/OpenSID/wiki-pbb/issues/9)
Jika akan melakukan pembatalan pembayaran diperlukan tombol pembatalan pada menu SPPT.

**Comment by FirlianiF** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/92
