### ISSUE TITLE
[BUG] Pesan login berhasil namun masih tetap dihalaman Login

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#5]
Baru install dan sudah mengikuti panduan https://github.com/OpenSID/wiki-pbb/wiki/Cara-Instalasi-PBB, kemudian ketika login muncul pesan berhasil namun masih tetap di halaman login. dicoba masuk ke halaman dashboard maupun setting tetap berada di halaman login.

Harapannya normal dapat login.

**Comment by scqolbu24** [comment]
pada https://github.com/OpenSID/wiki-pbb/wiki/Cara-Instalasi-PBB perlu ditambahkan langkah panduannya:

```
Salin dan ubah file .htaccess.example menjadi .htaccess
```

dan tambahkan logo

```
tambahkan logo dengan nama logo.png pada folder assets/logo/logo.png
```

dengan ditambahkan langkah tersebut maka sudah dapat berjalan login dengan normal, sehingga issue ini ditutup.

**Comment by andifahruddinakas** [comment]
> pada https://github.com/OpenSID/wiki-pbb/wiki/Cara-Instalasi-PBB perlu ditambahkan langkah panduannya:
> 
> ```
> Salin dan ubah file .htaccess.example menjadi .htaccess
> ```
> 
> dan tambahkan logo
> 
> ```
> tambahkan logo dengan nama logo.png pada folder assets/logo/logo.png
> ```
> 
> dengan ditambahkan langkah tersebut maka sudah dapat berjalan login dengan normal, sehingga issue ini ditutup.

Gunakan base_url() untuk asset, gunakan site_url() untuk lainnya agar bisa menggunakan index.php (.htaccess) atau tdk.
