### ISSUE TITLE
Buat Tombol Pembayaran secara masal.

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#50]
Sediakan tombol pembayaran secara masal agar mempercepat penginputan, dengan catatan nilai pembayaran dengan nilai pagu pajak sama, serta tanggal pembayaran yang diinput secara masal sama.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/219
