### ISSUE TITLE
Timeline Rekap Pembayaran (konversi ke laravel)

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#51]
Tahapan issue [#9 Bertahap konversi ke laravel untuk rilis 22.06](https://github.com/OpenSID/wiki-pbb/issues/9)
<img width="100%" alt="timeline" src="https://user-images.githubusercontent.com/68048807/171749666-00c80a49-070b-4272-814a-4e306291803e.PNG">

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/93
