### ISSUE TITLE
BUG : Edit SPPT dan Menampilkan Rekap Pembayaran

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#54]
Terjadi error pada edit sppt dan menampilkan rekap pembayaran belum bayar karena tabel relasi yang ke tabel rayon ada yang dihapus.

Edit SPPT
<img width="100%" alt="bug-edit-sppt" src="https://user-images.githubusercontent.com/68048807/173162973-d1e676dd-1c72-40dc-9bc9-f7366f199831.PNG">

Menampilkan Rekap Pembayaran Belum Bayar
![error](https://user-images.githubusercontent.com/68048807/173258061-549f739d-9856-45bc-8e4e-362529a228ac.JPG)

**Comment by FirlianiF** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/96
