### ISSUE TITLE
Menampilkan Nama Wajib Pajak di hasil Cetak Rekap SPPT

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/wiki-pbb#56]
Hasil Cetakan pdf Cetak Rekap di tambah menampilkan Nama Wajib Pajak
![Screenshot_197](https://user-images.githubusercontent.com/57133748/174034343-0e86d9c1-0b30-4f99-95ca-0b3d2b71968e.png)

**Comment by FirlianiF** [comment]
sudah dikerjakan melalui pr https://github.com/OpenSID/pbb_desa/pull/99
