### ISSUE TITLE
tampilkan rekap/progres pembayaran per rayon

### ISSUE THREAD

**Issue by makhbub** [OpenSID/wiki-pbb#57]
di desa kami, pembayaran di pull per rayon, setiap rayon bertanggung jawab atas pembayaran PBB di wilayahnya. 

saat ini, di aplikasi PBB sudah ada fitur rekap waktu pembayaran satu desa. alangkah baiknya bila fitur ini dikembangkan dengan diperinci menjadi rekap waktu pembayaran per rayon, sehingga nantinya akan lebih mudah mengecek progres penyetoran PBB per Rayon
![rekap pbb](https://user-images.githubusercontent.com/38773660/175199436-6eb45a3e-ee2f-4452-bf1e-0aab11f78103.jpg)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/194
