### ISSUE TITLE
BUG : tidak berhasil update favicon

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/wiki-pbb#59]
https://forum.opendesa.id/d/202-bagaimana-cara-mengatasi-gagal-ganti-favicon-aplikasi-pbb

**Comment by scqolbu24** [comment]
hanya perlu menjalankan perintah php artisan storage:link 
sudah ditambahkan di panduan https://panduan.opendesa.id/id/pbb/instalasi poin 13.
