### ISSUE TITLE
Search nama rayon

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/wiki-pbb#60]
![Screenshot_9](https://user-images.githubusercontent.com/57133748/178230515-626f9d7d-0ecf-4abf-8299-60a2d6b27480.png)

untuk search nama rayon tidak berfungsi,  tetapi untuk pencarian nomor sppt dan nama wajib pajak berfungsi

**Comment by scqolbu24** [comment]
Setelah dilakukan berbagai simulasi pada pencarian rayon dihasilkan sebagai berikut:
Berfungsi:
![berfungsi1](https://user-images.githubusercontent.com/68048807/181655572-5d2f5230-7caf-4409-9172-13ac921dc4a7.JPG)
![berfungsi2](https://user-images.githubusercontent.com/68048807/181655617-a048f6e2-f969-4ea8-92b2-95fee842bde3.JPG)

Tidak berfungsi:
![tidak berfungsi1](https://user-images.githubusercontent.com/68048807/181655641-d3d4e80a-4168-4ee5-bc2d-40fbace44ed7.JPG)
![tidak berfungsi2](https://user-images.githubusercontent.com/68048807/181655645-517ae7a5-c5a8-40ec-85c1-8491e3404e54.JPG)

Dari simulasi tersebut dapat disimpulkan jika pencariannya dengan kata yang menganduang sama dibaris yang lainnya maka akan ikut terfilter.

**Comment by scqolbu24** [comment]
Dari simulasi yang sudah dilakukan maka solusinya adalah dibuatkan filter untuk nama rayon atau nama rt menggunakan 'Option Select', sehingga untuk issue ini diubah menjadi fitur bukan sebagai bug.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/193
