### ISSUE TITLE
Notifikasi Info Peringatan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#62]
Saat ini untuk validasi token yang berlangganan premium, jika token tidak sesuai maka akan tampil peringatan berikut:

![info peringatan](https://user-images.githubusercontent.com/68048807/181180203-95989e94-e6d2-42a1-82c7-971759e6095d.jpg)

Dari peringatan tersebut perlu dirubah notifikasinya, salah satunya dibaris terakhir "Jika masih mengalami masalah harap menghubungi pelaksana masing-masing". 

Untuk Perubahan Notifikasi dapat didiskusikan di issue ini. 

Catatan:
Error tersebut terjadi ketika aplikasi PBB di install di localhost
Panduan Instalasi https://panduan.opendesa.id/id/pbb/instalasi#localhost

**Comment by scqolbu24** [comment]
Dari hasil pertemuan Tanggal 28 Juli 2022
1. Pastikan Anda telah berlangganan premium, jika belum berlangganan silahkan buka https://opendesa.id/mengonlinekan-opensid/ untuk berlanganan.
2. Mencari panduan di https://panduan.opendesa.id/id/pbb/instalasi
3. Jika masih mengalami masalah bisa berkonsultasi di https://forum.opendesa.id/t/pbb
4. Ejaan perlu diperbaiki.

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/112
