### ISSUE TITLE
Library/plugin Livewire dan Fortawesome pada aplikasi pbb belum berfungsi

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#65]
issue ini berdasarkan https://github.com/OpenSID/wiki-saas/issues/40
Pada saat menambahkan data sppt, pilihan rayon, rt, objek pajak dan subjek pajak belum dapat berfungsi karena komponen livewire belum di load. Ketika pada url ditambahkan pbb di depan livewire (pbb/livewire), maka livewire bisa di load.

selain itu fortawesome juga belum dapat di load.

kedua issue tersebut diatas disebabkan karena aplikasi pbb bukan diinstall pada domain sendiri (misalkan http://desacontoh.opendesa.id/pbb)

<img width="100%" alt="livewire" src="https://user-images.githubusercontent.com/68048807/178707027-99aaff5d-0d69-4757-b835-5f7566fbf661.PNG">

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/108
