### ISSUE TITLE
Menu tambah SPPT di perbaiki

### ISSUE THREAD

**Issue by sopyanpay** [OpenSID/wiki-pbb#67]
Ketika mau tambah SPPT muncul Luas bukan SPPT di maksud, 
setelah di klik objek Pajak muncul luas otomatis

**Comment by scqolbu24** [comment]
Pak @sopyanpay, mohon dibantu cara replikasinya bagaimana, Alur sampai terjadinya eror?.

**Comment by scqolbu24** [comment]
Sampai saat ini saya coba normal, jika masih terjadi di tempat bapak, issue ini di buka kembali dengan mengirimkan screenshot error tersebut.
