### ISSUE TITLE
ambil data penduduk dari aplikasi OpenSID

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/wiki-pbb#68]
belum bisa ambil data penduduk dari Aplikasi OpenSID di PBB,

**Comment by scqolbu24** [comment]
issue ini berkaitan dengan [issue #28 Sinkronisasi dengan OpenSID (konversi ke laravel) ](https://github.com/OpenSID/wiki-pbb/issues/28)

Fitur ini akan masuk di rilis 22.11.01.

berkaitan issue ini duplikat dan sudah dikerjakan pada PR https://github.com/OpenSID/pbb_desa/pull/131, maka issue ini ditutup.
