### ISSUE TITLE
[panambahan fitur] tampilan dashboard laporan PBB

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/wiki-pbb#69]
tampilan dashboard laporan PBB baiknya login terlebih dahulu

**Comment by scqolbu24** [comment]
Yang dimaksud bagaiman mas @devrakapriyo, sekarang sudah diterapkan seperti itu, tampilan awal login terlebih dahulu

**Comment by devrakapriyo** [comment]
baik mas, kalau sudah seperti itu saya close saja ya
