### ISSUE TITLE
BUG: Eror ketika cetak Laporan Rekap

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#70]
![error cetak](https://user-images.githubusercontent.com/68048807/185841797-2f3cba22-239d-45e9-9285-4dac028d4751.JPG)

Dibuatkan validasi pada form ceklist berikut:
- [x] Laporan rekap belum bayar
- [x] Laporan rekap lunas

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/116
