### ISSUE TITLE
Ubah Nama Bendahara menjadi Kaur Keuangan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#73]
berdasarkan usulan dari pelaksana ketika diskusi 26 Agustus 2022 bahwa nama bendahara diganti menjadi kaur keuangan.

**Comment by scqolbu24** [comment]
Setelah update ke 22.10 jalankan perintah:
php artisan migrate:refresh --path=/database/migrations/2022_05_09_140546_create_pengaturan_aplikasi_table.php
php artisan db:seed --class=Database\Seeders\Pengaturan\AplikasiSeeder

**Comment by scqolbu24** [comment]
> Setelah update ke 22.10 jalankan perintah: php artisan migrate:refresh --path=/database/migrations/2022_05_09_140546_create_pengaturan_aplikasi_table.php php artisan db:seed --class=Database\Seeders\Pengaturan\AplikasiSeeder

Ada perubahan perintah untuk menjalankan setelah dilakukan update ke versi 22.10,Adapun perintah tersebut:
php artisan pbb:migrate --db=true --migrasi=mulai

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/122
