### ISSUE TITLE
Penyesuaian pada Form SPPT

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#75]
Penempatan Subjek Pajak di atas Objek Pajak
Data Pemilik

**Comment by vickyrolanda** [comment]
Data Pemilik di input di subjek pajak. 
Penambahan Subjek Pajak Pemilik saat ini diambil dari data subject pajak  (penambahan)

1. Uratan nama subject dibuat berurut sesuai abjad
2. Subject pajak ditambahkan field NIK &  No HP (di kerjain untuk issue https://github.com/OpenSID/wiki-pbb/issues/97)
3. Urutan pilihan subject pajak - (NIK : Nama Subject Pajak ) 

![Image](https://user-images.githubusercontent.com/59082428/202183216-29ea79c1-4f40-4c86-942a-1a311e8bef94.png)

4. Lalu urutan pada form , subject pajak , pemilik , objek pajak.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/146
