### ISSUE TITLE
Penyebutan Rayon di atur pada Pengaturan Aplikasi

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#76]
Pada suatu wilayah ada yang menamakan rayon dan ada yang menamakan kolektor sehingga untuk penyebutan ini perlu disesuaikan.

**Comment by scqolbu24** [comment]
Setelah dilakukan update ke versi 22.10 jalankan perintah berikut:
php artisan pbb:migrate --db=true --migrasi=mulai

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/124
