### ISSUE TITLE
Pemisah Nominal pada Dashbord

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/wiki-pbb#82]
Misal Rp.  37.511.987,-

suapaya mudah membacanya

![Screenshot_53](https://user-images.githubusercontent.com/57133748/188471835-adf16312-0449-4e42-9f33-dd346ac7e1a9.png)

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/138
