### ISSUE TITLE
Tampilkan nama pemungut di rekap Pembayaran

### ISSUE THREAD

**Issue by ahmadngudi** [OpenSID/wiki-pbb#83]
Dipilihan Laporan Rekap ada nama rayon dan nama RT

![Screenshot_54](https://user-images.githubusercontent.com/57133748/188473805-1bfef775-05da-4ea6-a61e-4cccf4e8fcdb.png)

namun di hasil cetakan pdf hanya menampilkan Nama Rayon

![Screenshot_56](https://user-images.githubusercontent.com/57133748/188474510-68f77f3b-0894-41d4-ae68-1c7471fba1e6.png)

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/137
