### ISSUE TITLE
ubah external link css dan js ke local file css js

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-pbb#84]
saat pengguna tidak ada koneksi internet maka datatable tidak dapat menampilkan data, maka perlu external link css dan js di ubah ke memanggil link local css dan js

**Comment by scqolbu24** [comment]
@FirlianiF, aplikasi PBB seharusnya menggunakan koneksi internet, karena pada aplikasi ini terdapat validasi untuk mengecek ke layanan yang membutuhkan koneksi internet, jika aplikasi ini tidak terhubung dengan layanan maka aplikasi ini tidak dapat digunakan.
