### ISSUE TITLE
angka pbb harus 18 digit

### ISSUE THREAD

**Issue by mranca** [OpenSID/wiki-pbb#85]
contoh 73.07.030.016.001-0019.0

**Comment by scqolbu24** [comment]
Pak @mranca, mohon dijelaskan lebih detail apa yang dimaksud

**Comment by scqolbu24** [comment]
setelah konfirmasi melalui chat telegram dengan @mranca, issue ini sudah sesuai di versi 22.11.01, sehingga issue ini di tutup
