### ISSUE TITLE
Buat migrasi database otomatis ketika rilis terbaru

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#86]
Issue ini berakitan dengan issue:

- [x] https://github.com/OpenSID/wiki-pbb/issues/73
- [x] https://github.com/OpenSID/wiki-pbb/issues/76

issue ini juga berkaitan dengan Layanan OpenSID Siap Pakai, sehingga ketika ada perubahan pada database akan dilakukan secara otomatis.

**Comment by scqolbu24** [comment]
Jika akan melakukan migrasi manual dapat lakukan perintah berikut:
1. php artisan pbb:migrate --db=true
2. php artisan pbb:migrate

atau 
php artisan pbb:migrate --db=true --migrasi=mulai

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/122 dan https://github.com/OpenSID/pbb_desa/pull/124
