### ISSUE TITLE
BUG: Input Objek Pajak

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#87]
Ketika menambahkan detail objek pajak, jika diinput salah satu bumi atau bangunan saja maka dapat diinput, namun jika keduanya diinput tombol tambah tidak berfungsi.

berikut tampilan errornya:
![bug objek pajak](https://user-images.githubusercontent.com/68048807/190310488-470ec61d-ad86-48eb-ac1c-f1303c234f0b.JPG)

**Comment by Wiliyantoro** [comment]
![image](https://user-images.githubusercontent.com/44520382/190311219-0aaf3f99-fd53-42e5-b41d-d72e3524eeae.png)
 ini jika barengan di input letak o pajak, no blok dll dan detail objek pajak, tombol tambah tidak berfungsi juga, harus bolak balik

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/125
