### ISSUE TITLE
BUG: Export Data SPPT

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#89]
Issue ini berdasarkan laporan dari grup telegram `Pelanggan Fitur OpenSID` setelah rilis 22.10.01 yang diuji coba di https://demopbb.opendesa.id
Ketika Melakukan export SPPT terjadi eror yang disebabkan karena yang berelasi dengan tabel sppt yaitu subjek pajak telah dihapus, berikut tampilan erornya: 

![Image](https://user-images.githubusercontent.com/68048807/193432258-da40fb03-eb87-46fd-b611-c6feb168a3ba.JPG)

Harapannya tidak terjadi eror walaupun tabel yang berelasi telah dihapus.
Cek tabel yang berelasi lainnya.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/129
