### ISSUE TITLE
BUG:Instal PBB

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#91]
Issue ini berawal dari penelusuran OpenSID Siap Pakai yang tidak melakukan install PBB dan 5 versi sebelumnya (tags)

![bug pbb1](https://user-images.githubusercontent.com/68048807/195083199-645332d8-f1f1-4f7d-a755-79c8bee8aed7.JPG)

![bug pbb2](https://user-images.githubusercontent.com/68048807/195083232-d377e84c-cee6-4f94-97fc-e85545d22ffa.JPG)

Solusinya hapus file composer.lock

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/128
