### ISSUE TITLE
BUG:Impor SPPT

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#92]
Berdasarkan laporan di grup telegram oleh @mr Anca bahwasanya ketika melakukan impor data excel terjadi error 500, setelah dilakukan pengetesan bahwasanya terdapat kesalahan ketik pada file yang di impor, berikut kesalahan ketiknya:

Pada Sheet Rayon
![rayon](https://user-images.githubusercontent.com/68048807/195459437-a2cebcde-eb0b-46e0-ad49-b7fd5673a5e3.jpg)

Pada Sheet RT
![rt](https://user-images.githubusercontent.com/68048807/195459459-f9e7ef0e-1e7d-441d-9f9c-523e71ab347c.jpg)

Pada Sheet SPPT
![sppt](https://user-images.githubusercontent.com/68048807/195460106-ede38cd7-f192-4b32-af82-4fe79bd0b97c.JPG)

Kemudian terdapat eror yang diakibatkan impor data terlalu lama
![maximum execution time](https://user-images.githubusercontent.com/68048807/195460962-fedf34e5-5003-4481-a4eb-ed3107a7825d.JPG)

Harapannya error tersebut tidak menampilkan error 500, namun ditunjukan penyebab errornya.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/pbb_desa/pull/130
