### ISSUE TITLE
Buatkan Migrasi Database melalui Pengaturan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#94]
Saat ini setelah update versi terbaru diperlukan untuk menjalakan perintah: php artisan pbb:migrate --db=true --migrasi=mulai
pada issue ini harapannya dapat dibuatkan tombol tersebut di pengaturan untuk migrasi database.

**Comment by FirlianiF** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/136
