### ISSUE TITLE
Maksimal karakter pada input luas 

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-pbb#96]
Saat ini untuk input luas PBB hanya dibatasi 4 karakter, pada usulan di chat telegram oleh Pak Ketut Wiliyantoro ada yang sampai 5 karakter, sehingga perlu disesuaikan untuk batasan tersebut.

**Comment by FirlianiF** [comment]
SUdah dikerjakan melalui PR https://github.com/OpenSID/pbb_desa/pull/144
