### ISSUE TITLE
(PENAMBAHAN FITUR) Tambahkan Kolom Nama Pemilik Sekarang, NIK dan No HP pada Subjek Pajak

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/wiki-pbb#97]
Belum adanya kolom **Nama Pemilik Sekarang, NIK dan No. HP,** untuk komunikasi dan NIK digunakan untuk membedakan nama subjek pajak yang memiliki nama yang sama pada alamat yang sama.
**Dikarenakan subjek pajak terkadang tertulis nama pemilik tanah sebelumnya, sehingga diperlukan kolom nama pemilik sekarang.**

![image](https://user-images.githubusercontent.com/57661283/199656371-fedc36dc-6dff-432e-9c74-59c93fc75056.png)

**Yang diharapkan ada penambahan data kolom Nama Pemilik Sekarang, NIK dan No HP pada subjek pajak**.

**Comment by scqolbu24** [comment]
Mas @vickyrolanda minta tolong bantu analisis, terkait Nama Pemilik Sekarang kalau berdasarkan analisisi saya sepertinya lebih tepatnya ada di `SPPT` bukan di form `Subjek Pajak`.

**Comment by vickyrolanda** [comment]
Untuk penambahan field hanya Nik & no HP. sedangkan pemilik sekrang bisa di input sebagai subject pajak baru.
https://github.com/OpenSID/wiki-opensid-api/issues/1

**Comment by FirlianiF** [comment]
PR https://github.com/OpenSID/pbb_desa/pull/143
