### ISSUE TITLE
tombol ubah hilang jika data pbb hasil import

### ISSUE THREAD

**Issue by mranca** [OpenSID/wiki-pbb#98]
![Opera Snapshot_2022-11-06_020624_pbb tongketongke desa id](https://user-images.githubusercontent.com/76085245/200150988-359a097a-1668-4d7c-909c-4ecc0dcc290c.png)

**Comment by mranca** [comment]
tombol ubah itu ada di bagian menu sppt

**Comment by scqolbu24** [comment]
Pak @mranca, tombol ubah akan hilang jika status sudah `Lunas`.

**Comment by mranca** [comment]
Ok baik pak

**Comment by mranca** [comment]
Ok d close pak

**Comment by scqolbu24** [comment]
Baik pak issue ini ditutup
