### ISSUE TITLE
jumlah sppt pada dashboard masing-masing rayon tidak muncul saat import data 

### ISSUE THREAD

**Issue by mranca** [OpenSID/wiki-pbb#99]
![Uploading Opera Snapshot_2022-11-06_020739_pbb.tongketongke.desa.id.png…]()

**Comment by scqolbu24** [comment]
Pak @mranca, mohon ditampilkan screenshotnya apa yang dimaksud.

**Comment by mranca** [comment]
![Opera Snapshot_2022-11-06_020739_pbb tongketongke desa id](https://user-images.githubusercontent.com/76085245/200431350-a4389979-4002-422c-b7d0-d8645be0d479.png)
kalau hasil import datanya tidak bisa masuk pada masing-masing rayon, akan tetapi jika datanya diketik manual baru bisa menampilkan jumlah pada masing-masing rayon

**Comment by scqolbu24** [comment]
Setelah saya uji coba menggunakan data excel yang diberikan Pak @mranca, untuk import data dari excel tampil rekapan pencapaian rayon seperti berikut:
![replikasi issue99](https://user-images.githubusercontent.com/68048807/201857178-eea33c80-5917-490f-9942-18929c4f77e6.JPG)

Rekapan `Pencapaian Rayon` masuk ke `AGUS SYAM` semua dikarenakan untuk nama RT yang diisi pada sheet nama_rt sama semua yaitu `RT 000`, bisa diisie berbeda misalkan RT 001 RW 001, RT 001 RW 002
![replikasi issue99-1](https://user-images.githubusercontent.com/68048807/201858079-4998d2ee-307a-4f9f-bba3-53c965195f3e.JPG)


Kemudian untuk replikasi yang screenshoot pak @mranca apakah saya bisa minta datanya untuk saya uji coba.

**Comment by scqolbu24** [comment]
untuk tampilan dasbor ditempat pak @mranca seperti itu, apakah dikarenakan di zoom atau bagaimana pak?

**Comment by mranca** [comment]
Memang seperti itu pak, saya gunakan operamini untuk membukanya

**Comment by mranca** [comment]
Saya juga sudah membuat nama rt yang berbeda-beda namun  hasilnya tetap sama

**Comment by mranca** [comment]
saya bisa kasih password admin sempat mau di cek langsung pak

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/pbb_desa/pull/147
